### ISSUE TITLE
AssertionError问题求助

### ISSUE THREAD

**Issue by yangyahu-1994** [yijingru/BBAVectors-Oriented-Object-Detection#115]
(BBAVectors) yyh@ubuntu:~/Documents/BBAVectors-Oriented-Object-Detection$ python main.py --data_dir data_bbav --num_epoch 80 --batch_size 16 --dataset dota --phase train
Setting up data...
Starting training...
----------
Epoch: 1/80 
Traceback (most recent call last):
  File "main.py", line 58, in <module>
    ctrbox_obj.train_network(args)
  File "/home/yyh/Documents/BBAVectors-Oriented-Object-Detection/train.py", line 130, in train_network
    epoch_loss = self.run_epoch(phase='train',
  File "/home/yyh/Documents/BBAVectors-Oriented-Object-Detection/train.py", line 160, in run_epoch
    for data_dict in data_loader:
  File "/home/yyh/anaconda3/envs/BBAVectors/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/yyh/anaconda3/envs/BBAVectors/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/home/yyh/anaconda3/envs/BBAVectors/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/home/yyh/anaconda3/envs/BBAVectors/lib/python3.8/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/yyh/anaconda3/envs/BBAVectors/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/yyh/anaconda3/envs/BBAVectors/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yyh/anaconda3/envs/BBAVectors/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yyh/Documents/BBAVectors-Oriented-Object-Detection/datasets/base.py", line 256, in __getitem__
    image = self.load_image(index)
  File "/home/yyh/Documents/BBAVectors-Oriented-Object-Detection/datasets/dataset_dota.py", line 62, in load_image
    assert os.path.exists(imgFile), 'image {} not existed'.format(imgFile)
AssertionError: image data_bbav/images/P1871__0.5__5414___1500.png not existed

**Comment by yijingru** [comment]
" image data_bbav/images/P1871__0.5__5414___1500.png not existed"

**Comment by yangyahu-1994** [comment]
谢谢大佬，我把data_bbav写成dota_bbav了，现在已经跑起来了。

**Comment by yangyahu-1994** [comment]
谢谢大佬，我把data_bbav/images写成dota_bbav了，现在已经跑起来了
