### ISSUE TITLE
How to test example?

### ISSUE THREAD

**Issue by dkatona4** [yijingru/BBAVectors-Oriented-Object-Detection#58]
Hi,

I cannot run the program with the default example in test phase.

What i did:

Successfully ran the following command:
`python3 main.py --data_dir datasets/DOTA_devkit/example/ --num_epoch 80 --batch_size 1 --dataset dota --phase train`
The command worked perfectly and now I've got weights_dota folder, which contains the .pth neural networks.

After that, I would like to test the neural network, so i created a "datasets/DOTA_devkit/example/test.txt" file with the necessary filenames. The file contains only two row:
> P0706
> P0770

After the preparation I ran the following command:
`python3 main.py --data_dir datasets/DOTA_devkit/example/ --resume weights_dota/model_20.pth --dataset dota --phase test`

and I got the following output:

```
Traceback (most recent call last):
  File "main.py", line 61, in <module>
    ctrbox_obj.test(args, down_ratio=down_ratio)
  File "/home/project/programs/BBAVectors-Oriented-Object-Detection/test.py", line 128, in test
    nms_results = func_utils.non_maximum_suppression(pts_cat, scores_cat)
  File "/home/project/programs/BBAVectors-Oriented-Object-Detection/func_utils.py", line 45, in non_maximum_suppression
    keep_index = py_cpu_nms_poly_fast(dets=nms_item, thresh=0.1)
  File "/home/project/programs/BBAVectors-Oriented-Object-Detection/datasets/DOTA_devkit/ResultMerge_multi_process.py", line 74, in py_cpu_nms_poly_fast
    tm_polygon = polyiou.VectorDouble([dets[i][0], dets[i][1],
NameError: name 'polyiou' is not defined

```
I have no idea what should i do, because the training part worked flawlessly.
Have you ever met with this issue, or Am I missing something?

Thank you in advance for your help.

**Comment by yijingru** [comment]
It looks like you haven't download the [DOTA_devkit](https://github.com/CAPTAIN-WHU/DOTA_devkit), you may download and install first and put the folder under datasets.
