### ISSUE TITLE
map值过低，只有0.34513285971323016

### ISSUE THREAD

**Issue by DHU-JinQi** [yijingru/BBAVectors-Oriented-Object-Detection#66]
将代码上传到google drive，我希望测试该模型在DOTAv1.0的验证集的表现。在colab中运行。我将ResultMerge_multi_process.py中mergesingle函数改为：
```
def mergesingle(dstpath, nms, fullname):
    name = util.custombasename(fullname)
    #print('name:', name)
    dstname = os.path.join(dstpath, name + '.txt')
    with open(fullname, 'r') as f_in:
        nameboxdict = {}
        lines = f_in.readlines()
        splitlines = [x.strip().split(' ') for x in lines]
        for splitline in splitlines:
            subname = splitline[0]
            confidence = splitline[1]
            det = splitline[2:]
            det.append(confidence)
            det = list(map(float, det))
            if (subname not in nameboxdict):
                nameboxdict[subname] = []
            nameboxdict[subname].append(det)
        nameboxnmsdict = nmsbynamedict(nameboxdict, nms, nms_thresh)
        with open(dstname, 'w') as f_out:
            for imgname in nameboxnmsdict:
                for det in nameboxnmsdict[imgname]:
                    #print('det:', det)
                    confidence = det[-1]
                    bbox = det[0:-1]
                    outline = imgname + ' ' + \
                        str(confidence) + ' ' + ' '.join(map(str, bbox))
                    #print('outline:', outline)
                    f_out.write(outline + '\n')
```

运行主函数：
`! python /content/gdrive/MyDrive/BBAVectors-Oriented-Object-Detection-master/main.py --batch_size 16 --conf_thresh 0.1 --resume /content/gdrive/MyDrive/BBAVectors_rh_weights/model_50.pth --dataset dota --data_dir /content/gdrive/MyDrive/MYDOTA/val --phase eval`

再运行：
`! python /content/gdrive/MyDrive/BBAVectors-Oriented-Object-Detection-master/datasets/DOTA_devkit/dota_evaluation_task1.py`

进行测试。得到结果的最后两行为：
map: 0.33467535978602364
classaps:  [35.13236254 36.36363636  9.09090909 25.71428571 31.22519165 59.15453166
 24.70141191 81.63756773 42.81118881  9.09090909 50.55224277 16.81818182
 32.22000793 16.98113208 30.51948052]

请帮忙看看哪里出了问题，谢谢。

**Comment by DHU-JinQi** [comment]
除此以外，还修改了：
datasets/DOTA_devkit/ResultMerge_multi_process.py 第14行改为：
`    from . import dota_utils as util`


datasets/DOTA_devkit/ResultMerge_multi_process.py 第14行改为：
`from . import polyiou`

datasets/hrsc_evaluation_task1.py  第19行改为：
`from DOTA_devkit import polyiou`

datasets/DOTA_devkit/dota_evaluation_task1.py 里第281-283行的路径。

**Comment by yijingru** [comment]
你的`validation`数据是自己设置的吗，如果和`test`集distribution差别很大，会出现落差很正常。想知道代码有没有问题，你大可直接跑`test`，官网测一下就可以了。

关于代码：
`DOTA_devkit`我几乎没有改过，除了`ResultMerge_multi_process.py`的13-16改为
`
# try:
from . import dota_utils as util
# except:
#     from .dota_kit import dota_utils as util`
另外，请使用`merge_result`的结果上传，我会补充到`readme.md`

**Comment by DHU-JinQi** [comment]
使用的数据是原DOTA的val文件夹下数据，手动将其解压：
`!unzip /content/gdrive/MyDrive/DOTA/val/images/part1.zip -d /content/gdrive/MyDrive/MYDOTA/val >val.log`
`!unzip /content/gdrive/MyDrive/DOTA/val/labelTxt-v1.0/labelTxt.zip -d /content/gdrive/MyDrive/MYDOTA/val/labelTxt >val.log`

如果不修改ResultMerge_multi_process.py中mergesingle函数，则运行：
`! python /content/gdrive/MyDrive/BBAVectors-Oriented-Object-Detection-master/main.py --batch_size 16 --conf_thresh 0.1 --resume /content/gdrive/MyDrive/BBAVectors_rh_weights/model_50.pth --dataset dota --data_dir /content/gdrive/MyDrive/MYDOTA/val --phase eval`
会报错：
```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/content/gdrive/MyDrive/BBAVectors-Oriented-Object-Detection-master/datasets/DOTA_devkit/ResultMerge_multi_process.py", line 229, in mergesingle
    x_y_2 = re.findall(r'\d+', x_y[0])
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/BBAVectors-Oriented-Object-Detection-master/main.py", line 64, in <module>
    ctrbox_obj.evaluation(args, down_ratio=down_ratio)
  File "/content/gdrive/MyDrive/BBAVectors-Oriented-Object-Detection-master/eval.py", line 53, in evaluation
    dsets.merge_crop_image_results(result_path, merge_path)
  File "/content/gdrive/MyDrive/BBAVectors-Oriented-Object-Detection-master/datasets/dataset_dota.py", line 123, in merge_crop_image_results
    mergebypoly(result_path, merge_path)
  File "/content/gdrive/MyDrive/BBAVectors-Oriented-Object-Detection-master/datasets/DOTA_devkit/ResultMerge_multi_process.py", line 293, in mergebypoly
    py_cpu_nms_poly_fast)
  File "/content/gdrive/MyDrive/BBAVectors-Oriented-Object-Detection-master/datasets/DOTA_devkit/ResultMerge_multi_process.py", line 262, in mergebase_parallel
    pool.map(mergesingle_fn, filelist)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
IndexError: list index out of range
```
且merge_data下没有文件。如果使用result_data的数据，则map: 0.345。

如果运行：
`! python /content/gdrive/MyDrive/BBAVectors-Oriented-Object-Detection-master/main.py --batch_size 16 --conf_thresh 0.1 --resume /content/gdrive/MyDrive/BBAVectors_rh_weights/model_50.pth --dataset dota --data_dir /content/gdrive/MyDrive/MYDOTA/val --phase test`
输出：
```
loaded weights from /content/gdrive/MyDrive/BBAVectors_rh_weights/model_50.pth, epoch 50
processing 0/458 image ...
: cannot connect to X server 
```
可能与colab不能给访问图形程序的用户主机赋予xhost权限有关。

**Comment by yijingru** [comment]
> 使用的数据是原DOTA的val文件夹下数据，手动将其解压：
> `!unzip /content/gdrive/MyDrive/DOTA/val/images/part1.zip -d /content/gdrive/MyDrive/MYDOTA/val >val.log`
> `!unzip /content/gdrive/MyDrive/DOTA/val/labelTxt-v1.0/labelTxt.zip -d /content/gdrive/MyDrive/MYDOTA/val/labelTxt >val.log`
> 
> 如果不修改ResultMerge_multi_process.py中mergesingle函数，则运行：
> `! python /content/gdrive/MyDrive/BBAVectors-Oriented-Object-Detection-master/main.py --batch_size 16 --conf_thresh 0.1 --resume /content/gdrive/MyDrive/BBAVectors_rh_weights/model_50.pth --dataset dota --data_dir /content/gdrive/MyDrive/MYDOTA/val --phase eval`
> 会报错：
> 
> ```
> multiprocessing.pool.RemoteTraceback: 
> """
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
>     result = (True, func(*args, **kwds))
>   File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
>     return list(map(*args))
>   File "/content/gdrive/MyDrive/BBAVectors-Oriented-Object-Detection-master/datasets/DOTA_devkit/ResultMerge_multi_process.py", line 229, in mergesingle
>     x_y_2 = re.findall(r'\d+', x_y[0])
> IndexError: list index out of range
> """
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/content/gdrive/MyDrive/BBAVectors-Oriented-Object-Detection-master/main.py", line 64, in <module>
>     ctrbox_obj.evaluation(args, down_ratio=down_ratio)
>   File "/content/gdrive/MyDrive/BBAVectors-Oriented-Object-Detection-master/eval.py", line 53, in evaluation
>     dsets.merge_crop_image_results(result_path, merge_path)
>   File "/content/gdrive/MyDrive/BBAVectors-Oriented-Object-Detection-master/datasets/dataset_dota.py", line 123, in merge_crop_image_results
>     mergebypoly(result_path, merge_path)
>   File "/content/gdrive/MyDrive/BBAVectors-Oriented-Object-Detection-master/datasets/DOTA_devkit/ResultMerge_multi_process.py", line 293, in mergebypoly
>     py_cpu_nms_poly_fast)
>   File "/content/gdrive/MyDrive/BBAVectors-Oriented-Object-Detection-master/datasets/DOTA_devkit/ResultMerge_multi_process.py", line 262, in mergebase_parallel
>     pool.map(mergesingle_fn, filelist)
>   File "/usr/lib/python3.6/multiprocessing/pool.py", line 266, in map
>     return self._map_async(func, iterable, mapstar, chunksize).get()
>   File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
>     raise self._value
> IndexError: list index out of range
> ```
> 
> 且merge_data下没有文件。如果使用result_data的数据，则map: 0.345。
> 
> 如果运行：
> `! python /content/gdrive/MyDrive/BBAVectors-Oriented-Object-Detection-master/main.py --batch_size 16 --conf_thresh 0.1 --resume /content/gdrive/MyDrive/BBAVectors_rh_weights/model_50.pth --dataset dota --data_dir /content/gdrive/MyDrive/MYDOTA/val --phase test`
> 输出：
> 
> ```
> loaded weights from /content/gdrive/MyDrive/BBAVectors_rh_weights/model_50.pth, epoch 50
> processing 0/458 image ...
> : cannot connect to X server 
> ```
> 
> 可能与colab不能给访问图形程序的用户主机赋予xhost权限有关。

`result_dota`数据是区分了`0.5`和`1.0`scale的，没有merge的话测量不对，除非你没有分两个scale。报错的话可能是因为merge找的文件名不对，跟图形程序无关的

**Comment by DHU-JinQi** [comment]
“除非你没有分两个scale”这句话是啥意思，怎么实现？

result_dota/Task1_tennis-court.txt下的数据是这样：
```
P2733 0.322204530239 542.7 818.8 569.5 865.2 483.8 909.0 457.0 862.6
P2733 0.308642119169 1961.0 2486.8 2017.2 2508.1 1974.1 2611.2 1917.9 2589.9
P2733 0.123543329537 1855.7 2385.2 1926.3 2423.4 1843.6 2547.8 1773.1 2509.6
P2050 0.837271988392 265.1 363.6 265.1 454.3 225.8 454.3 225.8 363.6
P2050 0.795706748962 278.7 195.9 278.7 286.3 238.4 286.3 238.4 195.9
P2050 0.793210148811 546.7 203.9 546.7 299.1 507.1 299.1 507.1 203.9
P2050 0.786719977856 336.8 511.5 336.8 604.1 296.3 604.1 296.3 511.5
P2050 0.775522291660 224.7 497.7 260.7 500.1 256.3 590.7 220.3 588.2
...
```

**Comment by yijingru** [comment]
> “除非你没有分两个scale”这句话是啥意思，怎么实现？
> 
> result_dota/Task1_tennis-court.txt下的数据是这样：
> 
> ```
> P2733 0.322204530239 542.7 818.8 569.5 865.2 483.8 909.0 457.0 862.6
> P2733 0.308642119169 1961.0 2486.8 2017.2 2508.1 1974.1 2611.2 1917.9 2589.9
> P2733 0.123543329537 1855.7 2385.2 1926.3 2423.4 1843.6 2547.8 1773.1 2509.6
> P2050 0.837271988392 265.1 363.6 265.1 454.3 225.8 454.3 225.8 363.6
> P2050 0.795706748962 278.7 195.9 278.7 286.3 238.4 286.3 238.4 195.9
> P2050 0.793210148811 546.7 203.9 546.7 299.1 507.1 299.1 507.1 203.9
> P2050 0.786719977856 336.8 511.5 336.8 604.1 296.3 604.1 296.3 511.5
> P2050 0.775522291660 224.7 497.7 260.7 500.1 256.3 590.7 220.3 588.2
> ...
> ```

Aerial图片是很大的，你似乎没有进行split. 具体细节可以参考文章，或者[ROITransformer](https://arxiv.org/pdf/1812.00155.pdf)，操作可以参考[DOTA_devkit](https://github.com/CAPTAIN-WHU/DOTA_devkit)

**Comment by DHU-JinQi** [comment]
好了，谢谢。
`map: 0.7818542376483315
classaps:  [90.55680899 87.46188713 51.63154236 78.4597352  64.16890956 80.14791688
 86.24186688 90.86889567 87.81427833 80.48762305 78.25639579 73.76626134
 77.22576934 63.92475992 81.76870603]`

**Comment by yijingru** [comment]
> 好了，谢谢。
> `map: 0.7818542376483315 classaps: [90.55680899 87.46188713 51.63154236 78.4597352 64.16890956 80.14791688 86.24186688 90.86889567 87.81427833 80.48762305 78.25639579 73.76626134 77.22576934 63.92475992 81.76870603]`

恭喜，有空的话也可以试试`test`集

**Comment by gewenchao** [comment]
> > “除非你没有分两个scale”这句话是啥意思，怎么实现？
> > result_dota/Task1_tennis-court.txt下的数据是这样：
> > ```
> > P2733 0.322204530239 542.7 818.8 569.5 865.2 483.8 909.0 457.0 862.6
> > P2733 0.308642119169 1961.0 2486.8 2017.2 2508.1 1974.1 2611.2 1917.9 2589.9
> > P2733 0.123543329537 1855.7 2385.2 1926.3 2423.4 1843.6 2547.8 1773.1 2509.6
> > P2050 0.837271988392 265.1 363.6 265.1 454.3 225.8 454.3 225.8 363.6
> > P2050 0.795706748962 278.7 195.9 278.7 286.3 238.4 286.3 238.4 195.9
> > P2050 0.793210148811 546.7 203.9 546.7 299.1 507.1 299.1 507.1 203.9
> > P2050 0.786719977856 336.8 511.5 336.8 604.1 296.3 604.1 296.3 511.5
> > P2050 0.775522291660 224.7 497.7 260.7 500.1 256.3 590.7 220.3 588.2
> > ...
> > ```
> 
> Aerial图片是很大的，你似乎没有进行split. 具体细节可以参考文章，或者[ROITransformer](https://arxiv.org/pdf/1812.00155.pdf)，操作可以参考[DOTA_devkit](https://github.com/CAPTAIN-WHU/DOTA_devkit)

作者你好，请问一下你split用的是[DOTA_devkit](url)中的Img.Split.py  还是 imgSplit_multi_process.py
